### PR TITLE
JHED connection

### LINKED ISSUE #149: Logging in different accounts and trying to connect to existing accounts causes an AuthAlreadyAssociated exception
Steps to reproduce:

Suppose there are no students in student_student.
1. Log in with Facebook
2. Log out
3. Log in with Google/JHU
4. Click on Continue with Facebook
5. Log in with the same Facebook account
6. AuthAlreadyAssociated exception is raised

Potential solution:
- [ ] Extend the social pipeline to catch this error
- [ ] Create a modal informing users to delete their existing account
- [ ] Redirect users to this modal

### PR DESCRIPTION
**Pull request by JJamesWWang**
- Adds option to log in with JHU -> Sets the Student model's jhed field
- Add an advising dashboard button that redirects to /advising or shows a modal telling students to sign in with JHU
- Add a new modal that can be edited to fit the JHU signup requirement
- Add a field to student serializer to check for whether a student is signed in with JHU
- Fixes #149 with a new modal and django middleware class

### CODE REVIEW

**Comment by miaboloix** [comment]
Screen Shot 2021-03-25 at 8 54 05 PM

I'm getting this error - is there something I need to configure or is this a bug?

**Comment by JJamesWWang** [comment]
> I'm getting this error - is there something I need to configure or is this a bug?

@miaboloix Weird, I haven't had an error like that for a while. Are you using https when logging in? https://jhu.sem.ly?

**Review by miaboloix — APPROVED** [review]

File: static/js/redux/init.jsx [hunk 1]
```diff
@@ -1,204 +1,205 @@
-/*
```
Comment (alihacks) [inline static/js/redux/init.jsx:1]: Why is this showing as entire file change?

Comment (miaboloix) [reply static/js/redux/init.jsx:1]: this has been happening every time someone alters `init.jsx` (see jeanie's PR https://github.com/jhuopensource/semesterly/pull/152/files#diff-51b3d0226cab8b1f22378afdccd04fd620de498f2d4c0745d4357340dee1c04a) - I am not sure why. At first I thought that maybe it was a difference in spacing btw his IDE and here but I'm not sure why this would only affect this file?

**Review by Boccca2014 — APPROVED** [review]
